server:
  port: 7002
  #servlet:
  #  context-path: /@project.artifactId@
#nacos服务地址及账号密码
nacos:
  server-addr: localhost:8848
  namespace: test
  username: nacos
  password: nacos
  group: biz
  file-extension: yaml
  # app-name: ${spring.application.name}
hostname: ${HOSTNAME:logs}