server:
  port: 7004
  #servlet:
  #  context-path: /@project.artifactId@
#nacos服务地址及账号密码
nacos:
  server-addr: 172.25.224.135:18848
  namespace: biz
  username: nacos
  password: nacos
  group: biz
  file-extension: yaml
  # app-name: ${spring.application.name}
hostname: ${HOSTNAME:logs}